<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="snapUML_closed" nsURI="snapUML_closed" nsPrefix="snapUML_closed">
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessor" eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="D3Printer" eSuperTypes="#//Class">
    <eOperations name="reset"/>
    <eOperations name="connect"/>
    <eOperations name="sendCADFile"/>
    <eOperations name="print"/>
    <eOperations name="pause"/>
    <eOperations name="continue"/>
    <eOperations name="stop"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tempTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="printerSM" eType="#//PrinterStateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statemachines" upperBound="-1"
        eType="#//StateMachine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="snapshotmodel" lowerBound="1"
        eType="#//SnapshotModel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrinterStateMachine" eSuperTypes="#//StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="s2" lowerBound="1" eType="#//Connected"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s1" lowerBound="1" eType="#//StandBy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t1" lowerBound="1" eType="#//connect"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s3" lowerBound="1" eType="#//Operational"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s4" lowerBound="1" eType="#//Printing"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s5" lowerBound="1" eType="#//PausePrinting"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s6" lowerBound="1" eType="#//CancelPrinting"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t2" lowerBound="1" eType="#//sendCADFile"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t3" lowerBound="1" eType="#//print"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t4" lowerBound="1" eType="#//pause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t5" lowerBound="1" eType="#//continue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t6" lowerBound="1" eType="#//stop"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t7" lowerBound="1" eType="#//finished"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t8" lowerBound="1" eType="#//finished.1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s7" lowerBound="1" eType="#//Error"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t9" lowerBound="1" eType="#//error"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t10" lowerBound="1" eType="#//error.1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t11" lowerBound="1" eType="#//error.2"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t12" lowerBound="1" eType="#//error.3"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t13" lowerBound="1" eType="#//error.4"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t14" lowerBound="1" eType="#//error.5"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t15" lowerBound="1" eType="#//reset"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connected">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActiveTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" defaultValueLiteral="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//State"
        changeable="false" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandBy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActiveTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" defaultValueLiteral="true" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//State"
        changeable="false" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="connect">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//Connected"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//StandBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operational">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" defaultValueLiteral="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActiveTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//State"
        changeable="false" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="sendCADFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Connected"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//Operational"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="print">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Operational"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//Printing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="finished">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//CancelPrinting"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//StandBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="pause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Printing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//PausePrinting"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="stop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Printing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//CancelPrinting"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="continue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//PausePrinting"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//Printing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="finished">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Printing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//StandBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Printing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" defaultValueLiteral="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActiveTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//State"
        changeable="false" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PausePrinting">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActiveTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" defaultValueLiteral="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//State"
        changeable="false" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CancelPrinting">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActiveTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" defaultValueLiteral="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//State"
        changeable="false" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="error">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//Error"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//StandBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Error">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActiveTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="False"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" defaultValueLiteral="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//State"
        changeable="false" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="error">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//Error"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Connected"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="error">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//Error"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Operational"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="error">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//Error"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Printing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="error">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//Error"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//PausePrinting"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="error">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//Error"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//CancelPrinting"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="reset">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//StandBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//Error"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Transition"
        changeable="false" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firesTELEMETRY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SnapshotModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="snapshot" upperBound="-1"
        eType="#//Snapshot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Snapshot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Snapshot"
        eOpposite="#//Snapshot/previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Snapshot"
        eOpposite="#//Snapshot/next"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="d3printer" upperBound="-1"
        eType="#//D3Printer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="printerstatemachine" upperBound="-1"
        eType="#//PrinterStateMachine"/>
  </eClassifiers>
</ecore:EPackage>
